shuffle = true
library_tabs = ["playlists", "podcasts"]
repeat = "playlist"
hide_display_names = true

[theme]
background = "{background}"
primary = "{foreground}"
title = "{color14}"
playing = "{color14}"
playing_selected = "{color14}"
highlight = "{color14}"
highlight_bg = "{color10}"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "{color14}"
statusbar_bg = "{color14}"
cmdline = "#CBFFDE"
cmdline_bg = "#444444"
